name: Deploy to lambda
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Directly specify the region here
          aws_region: "us-east-1"
          function_name: FetchResumeFunction
          source: src/lambda_function.py
