name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy_zip:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Lambda function
        run: |
          mkdir -p package
          cp -r src/* package/
          pip install -r requirements.txt -t package/
          cd package
          zip -r ../lambda_function.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: your-lambda-function-name
          zip_file: lambda_function.zip
          handler: lambda_function.lambda_handler
          runtime: python3.8
          role: arn:aws:iam::xxxxxxxxxxx:role/your-lambda-role
          memory_size: 128
          timeout: 10
